In [138]:
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()

In [139]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [140]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=100)

In [141]:
#hyper parameter tuning
from sklearn.svm import SVC
model = SVC(kernel= 'rbf', C=30, gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9777777777777777

In [142]:
from sklearn.model_selection import cross_val_score


In [143]:
cross_val_score(SVC(kernel='linear', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [144]:
cross_val_score(SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)


array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [145]:
cross_val_score(SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [146]:
kernels = ['rbf', 'linear']
C = [1, 10, 20, 30]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel=kval, C=cval, gamma='auto'), iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96}

In [147]:
#same loop using sklearn
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10, 20]}
model = SVC()
clf = GridSearchCV(model, parameters, cv=5)
clf.fit(iris.data, iris.target)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 10, 20], 'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [148]:
sorted(clf.cv_results_.keys())

['mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'param_C',
 'param_kernel',
 'params',
 'rank_test_score',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'split3_test_score',
 'split4_test_score',
 'std_fit_time',
 'std_score_time',
 'std_test_score']

In [149]:
clf.cv_results_

{'mean_fit_time': array([0.00119958, 0.00179896, 0.0021986 , 0.00199456, 0.00219836,
        0.00199904]),
 'std_fit_time': array([3.99780899e-04, 7.47653045e-04, 1.46894525e-03, 7.40465314e-06,
        1.16513297e-03, 8.94415809e-04]),
 'mean_score_time': array([0.00059972, 0.00099883, 0.00119891, 0.00100288, 0.00119982,
        0.00079989]),
 'std_score_time': array([4.89669917e-04, 6.31957425e-04, 7.48099309e-04, 4.62458300e-06,
        4.00140554e-04, 3.99950133e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'ker

In [150]:
import pandas as pd
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001200      0.000400         0.000600        0.000490       1   
1       0.001799      0.000748         0.000999        0.000632       1   
2       0.002199      0.001469         0.001199        0.000748      10   
3       0.001995      0.000007         0.001003        0.000005      10   
4       0.002198      0.001165         0.001200        0.000400      20   
5       0.001999      0.000894         0.000800        0.000400      20   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
1          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
2       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
5          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.966667           0.966667                1.0   
1           0.966667           0.966667           0.933333                1.0   
2           1.000000           0.900000           0.966667                1.0   
3           1.000000           0.966667           0.966667                1.0   
4           1.000000           0.900000           0.933333                1.0   
5           1.000000           0.966667           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.966667        0.021082                5  
2         0.973333        0.038873                4  
3         0.980000        0.016330                1  
4         0.966667        0.042164                5  
5         0.980000        0.016330                1

In [151]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1       1          rbf         0.966667
2      10       linear         0.973333
3      10          rbf         0.980000
4      20       linear         0.966667
5      20          rbf         0.980000

In [152]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_required_parameters',
 '_run_search',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'refit_time_',
 'return_train_score',
 'score

In [153]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [154]:
clf.best_score_

0.9800000000000001

In [155]:
from sklearn.model_selection import RandomizedSearchCV

In [156]:
rs = RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[1, 10, 20],
    'kernel': ['rbf', 'linear']
    },
    cv=5,
    return_train_score=False,
    n_iter=2
)

In [157]:
rs.fit(iris.data, iris.target)
# pd.DataFrame(rs.cv_result_)[['param_C', 'param_kernel', 'mean_test_score']]

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                 class_weight=None, coef0=0.0,
                                 decision_function_shape='ovr', degree=3,
                                 gamma='auto', kernel='rbf', max_iter=-1,
                                 probability=False, random_state=None,
                                 shrinking=True, tol=0.001, verbose=False),
                   iid='deprecated', n_iter=2, n_jobs=None,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

In [158]:
dir(rs)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_required_parameters',
 '_run_search',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_iter',
 'n_jobs',
 'n_splits_',
 'param_distributions',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'random_state',
 'refit',
 'refit_t

In [159]:
rs.cv_results_

{'mean_fit_time': array([0.00059862, 0.00759521]),
 'std_fit_time': array([0.00048878, 0.01269807]),
 'mean_score_time': array([0.00040045, 0.00080032]),
 'std_score_time': array([0.00049045, 0.00040016]),
 'param_kernel': masked_array(data=['linear', 'rbf'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[10, 10],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'linear', 'C': 10}, {'kernel': 'rbf', 'C': 10}],
 'split0_test_score': array([1.        , 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.97333333, 0.98      ]),
 'std_test_score': array([0.03887301, 0.01632993]),
 'rank_test_score': array([2, 1])}

In [160]:
df = pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]
df

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      10          rbf         0.980000

WHich model fit best

In [161]:
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [162]:
Gb = MultinomialNB()
dir(Gb)
Gb.get_params()

{'alpha': 1.0, 'class_prior': None, 'fit_prior': True}

In [163]:
model_params ={
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest':{
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression':{
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params': {
            'C': [1, 5, 10]
        }
    },
    'MultinomialNB':{
        'model': MultinomialNB(),
        'params':{}
    },
    'GaussianNB':{
        'model': GaussianNB(),
        'params':{}
    },
    'DecissionTree':{
        'model': DecisionTreeClassifier(),
        'params':{
            'criterion':['gini', 'entropy'],
            'splitter': ['best', 'random']
        }
    }
}

In [164]:
scores = []
for model_names, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv = 5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model' : model_names,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [165]:
df = pd.DataFrame(scores, columns = ['model', 'best_score', 'best_params'])
df

model  best_score                                best_params
0                  svm    0.980000                  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333                        {'n_estimators': 5}
2  logistic_regression    0.966667                                   {'C': 5}
3        MultinomialNB    0.953333                                         {}
4           GaussianNB    0.953333                                         {}
5        DecissionTree    0.960000  {'criterion': 'gini', 'splitter': 'best'}