In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

C:\Users\hp\miniconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\hp\miniconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
df = pd.read_csv('homeprice.csv')

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
model.predict([[3300]])

array([629743.15068493])

In [6]:
#use for save model
import pickle

In [7]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [8]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [9]:
mp.predict([[3300]])

array([629743.15068493])

In [10]:
from sklearn.externals import joblib

In [11]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [12]:
mj = joblib.load('model_joblib')

In [13]:
mj.predict([[3300]])

array([629743.15068493])